import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.opencsv.CSVParser;
import com.opencsv.CSVParserBuilder;
import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.exceptions.CsvException;

/**
 * Convert Sage 50 Sales CSV exports into a JSON structure for Neo4j loading.
 *
 * Supports two export formats, auto-detected from the header row:
 *   - LEGACY   (Sales.csv)    – per-customer rows, summary rows close each invoice
 *   - NEW_SAGE (NewSales.CSV) – per-distribution rows grouped by Invoice/CM #
 *
 * Output shape:
 * {
 *   "invoices": [ Invoice, ... ]
 * }
 *
 * Usage (Maven):
 *   mvn exec:java -Dexec.mainClass="SalesToInvoiceJson" \
 *                 -Dexec.args="output.json [/NewSales.CSV]"
 *
 * Default CSV resource: /NewSales.CSV
 */
public class SalesToInvoiceJson {

    // =========================================================================
    // Data model
    // =========================================================================

    public static class Root {
        public List<Invoice> invoices = new ArrayList<>();
    }

    public static class Invoice {
        public int invoiceId;
        /** Original Sage Invoice/CM # – preserved for traceability; new IDs are generated by startId + sequence. */
        public String sourceInvoiceNumber;
        public LocalDate invoiceDate;
        public String notes;
        public BigDecimal totalQty;
        public BigDecimal totalAmount;
        public BigDecimal totalCostOfSales;
        public BigDecimal totalGrossProfit;
        public BigDecimal totalGrossMarginPercent;
        public String sourceCustomerId;
        public Customer customer;
        public Vehicle vehicle;
        public List<InvoiceLine> lines = new ArrayList<>();
    }

    public static class Customer {
        public String customerId;
        public String name;
        public String billToContact;
        public String phone;
    }

    public static class Vehicle {
        public int year;
        public String make;
        public String model;
        public String description;
        public String vin;
        public int mileage;
    }

    public static class InvoiceLine {
        public int sortOrder;
        public String itemId;
        public String itemDescription;
        public String stockingUm;
        public BigDecimal qty;
        public BigDecimal amount;
        public BigDecimal costOfSales;
        public BigDecimal grossProfit;
        public BigDecimal grossMarginPercent;
        public String serialNumber;
        public String serialNumberStatus;
        public String itemType;
        public String itemCategory;
        public boolean isCommentOnly;
    }

    // =========================================================================
    // CSV format detection + column mapping
    // =========================================================================

    private enum CsvFormat { LEGACY, NEW_SAGE }

    /**
     * Dynamic column-index map built from the first (header) row of the CSV.
     * Every field defaults to -1 (not present); safeGet() handles that gracefully.
     */
    private static class ColumnMap {
        CsvFormat format;

        // ---- Common ----
        int customerId   = -1;
        int date         = -1;
        int itemId       = -1;
        int qty          = -1;
        int amount       = -1;
        int itemDesc     = -1;
        int serialNumber = -1;
        int stockingUm   = -1;

        // ---- LEGACY-only ----
        int name          = -1;
        int billToContact = -1;
        int phone         = -1;
        int costOfSales   = -1;
        int grossProfit   = -1;
        int grossMargin   = -1;
        int serialStatus  = -1;
        int itemType      = -1;
        int itemCategory  = -1;

        // ---- NEW_SAGE-only ----
        int invoiceCmNum = -1;   // "Invoice/CM #"
        int shipToName   = -1;   // "Ship to Name"
        int invoiceNote  = -1;   // "Invoice Note"
        int invoiceDist  = -1;   // "Invoice/CM Distribution"  (0 = tax header; ≥1 = lines)
        int creditMemo   = -1;   // "Credit Memo"
        int unitPrice    = -1;   // "Unit Price"
    }

    private static ColumnMap buildColumnMap(String[] header) {
        ColumnMap cm = new ColumnMap();
        for (int i = 0; i < header.length; i++) {
            switch (header[i].trim().toLowerCase(Locale.ROOT)) {
                case "customer id"             -> cm.customerId    = i;
                case "name"                    -> cm.name          = i;
                case "item id"                 -> cm.itemId        = i;
                case "bill to contact"         -> cm.billToContact = i;
                case "last inv date"           -> cm.date          = i;
                case "date"                    -> { if (cm.date        == -1) cm.date        = i; }
                case "telephone 1"             -> cm.phone         = i;
                case "qty"                     -> cm.qty           = i;
                case "quantity"                -> { if (cm.qty         == -1) cm.qty         = i; }
                case "stocking u/m"            -> cm.stockingUm    = i;
                case "u/m id"                  -> { if (cm.stockingUm  == -1) cm.stockingUm  = i; }
                case "amount"                  -> cm.amount        = i;
                case "cost of sales"           -> cm.costOfSales   = i;
                case "gross profit"            -> cm.grossProfit   = i;
                case "gross margin"            -> cm.grossMargin   = i;
                case "item description"        -> cm.itemDesc      = i;
                case "description"             -> { if (cm.itemDesc    == -1) cm.itemDesc    = i; }
                case "serial number"           -> cm.serialNumber  = i;
                case "serial number status"    -> cm.serialStatus  = i;
                case "item class"              -> cm.itemType      = i;
                case "description for sales"   -> cm.itemCategory  = i;
                // New Sage
                case "invoice/cm #"            -> cm.invoiceCmNum  = i;
                case "ship to name"            -> cm.shipToName    = i;
                case "invoice note"            -> cm.invoiceNote   = i;
                case "invoice/cm distribution" -> cm.invoiceDist   = i;
                case "credit memo"             -> cm.creditMemo    = i;
                case "unit price"              -> cm.unitPrice     = i;
            }
        }
        cm.format = (cm.invoiceCmNum >= 0) ? CsvFormat.NEW_SAGE : CsvFormat.LEGACY;
        return cm;
    }

    // =========================================================================
    // Constants
    // =========================================================================

    private static final DateTimeFormatter DATE_FMT    = DateTimeFormatter.ofPattern("M/d/yy");
    private static final DateTimeFormatter DATE_FMT_4Y = DateTimeFormatter.ofPattern("M/d/yyyy");

    /** New invoice IDs are generated as startId + sequence. Set before calling convertCsvToInvoices if needed. */
    private static int startId = 0;

    // =========================================================================
    // Entry point
    // =========================================================================

    /**
     * args[0] = output JSON path
     * args[1] = CSV classpath resource (optional, default /NewSales.CSV)
     */
    public static void main(String[] args) throws IOException, CsvException {
        if (args.length < 1) {
            System.err.println("Usage: java SalesToInvoiceJson <outputJsonPath> [<csvResourcePath>]");
            System.exit(1);
        }

        String outputJson   = args[0];
        String resourcePath = args.length >= 2 ? args[1] : "/NewSales.CSV";

        InputStream csvStream = SalesToInvoiceJson.class.getResourceAsStream(resourcePath);
        if (csvStream == null) {
            throw new IllegalStateException("Could not find CSV on classpath at: " + resourcePath);
        }

        Root root = convertCsvToInvoices(csvStream);

        ObjectMapper mapper = new ObjectMapper()
                .enable(SerializationFeature.INDENT_OUTPUT)
                .findAndRegisterModules();                        // registers JavaTimeModule
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);

        mapper.writeValue(Paths.get(outputJson).toFile(), root);
        System.out.printf("Written %d invoices to %s%n", root.invoices.size(), outputJson);
    }

    // =========================================================================
    // Public API
    // =========================================================================

    public static Root convertCsvToInvoices(InputStream csvStream) throws IOException, CsvException {
        Root root = new Root();

        // Buffer the entire stream so we can detect format from the header first,
        // then re-read with the appropriate CSV parser settings.
        byte[] csvBytes = csvStream.readAllBytes();

        // ── Step 1: read header row only (default parser is fine for headers) ──
        ColumnMap cm;
        try (CSVReader headerReader = new CSVReader(
                new InputStreamReader(new ByteArrayInputStream(csvBytes), StandardCharsets.UTF_8))) {
            String[] header = headerReader.readNext();
            if (header == null) return root;
            cm = buildColumnMap(header);
        }

        // ── Step 2: re-parse the full CSV with a format-appropriate parser ──────
        //
        // NEW_SAGE: historic Sage exports contain malformed quoted fields
        //   (e.g. `"16" PACER 164P"`) that cause strict RFC-4180 parsers to
        //   throw "Unterminated quoted field".  Using withIgnoreQuotations(true)
        //   treats quote characters as literal text, which is safe because the
        //   NEW_SAGE format does not use quoted fields to embed commas.
        //
        // LEGACY: must use proper quoting because description / mileage fields
        //   legitimately embed commas (e.g. `"2003 Honda CR-V MILEAGE: 194,275"`).
        CSVParser csvParser = new CSVParserBuilder()
                .withIgnoreQuotations(cm.format == CsvFormat.NEW_SAGE)
                .build();

        try (CSVReader reader = new CSVReaderBuilder(
                new InputStreamReader(new ByteArrayInputStream(csvBytes), StandardCharsets.UTF_8))
                .withCSVParser(csvParser)
                .build()) {

            List<String[]> rows = reader.readAll();
            if (rows.isEmpty()) return root;

            if (cm.format == CsvFormat.NEW_SAGE) {
                convertNewSage(rows, cm, root);
            } else {
                convertLegacy(rows, cm, root);
            }
        }
        return root;
    }

    // =========================================================================
    // LEGACY format  (Sales.csv)
    // =========================================================================

    private static void convertLegacy(List<String[]> rows, ColumnMap cm, Root root) {
        Invoice currentInvoice = null;
        int invoiceSeq = 1;

        for (int i = 1; i < rows.size(); i++) {
            String[] row = rows.get(i);
            if (isRowEmpty(row)) continue;

            // Summary row: close the current invoice with totals
            if (isSummaryRow(row, cm)) {
                if (currentInvoice != null) {
                    applySummaryToInvoice(currentInvoice, row, cm);
                    finalizeInvoice(currentInvoice);
                    root.invoices.add(currentInvoice);
                    currentInvoice = null;
                }
                continue;
            }

            String rowCustomerId   = safeGet(row, cm.customerId);
            String rowCustomerName = safeGet(row, cm.name);
            LocalDate rowDate      = parseDate(safeGet(row, cm.date));
            boolean hasCustomer    = !isBlank(rowCustomerId) || !isBlank(rowCustomerName);

            if (currentInvoice == null) {
                if (!hasCustomer) continue;
                currentInvoice = openInvoice(invoiceSeq++, rowCustomerId, rowDate,
                        buildCustomerFromRow(row, cm));
            } else {
                String curId   = currentInvoice.customer.customerId == null ? "" : currentInvoice.customer.customerId;
                String curName = currentInvoice.customer.name       == null ? "" : currentInvoice.customer.name;
                boolean sameCustomer =
                        curId.equalsIgnoreCase(rowCustomerId) &&
                        curName.equalsIgnoreCase(rowCustomerName);
                boolean sameDate =
                        (currentInvoice.invoiceDate == null && rowDate == null) ||
                        (currentInvoice.invoiceDate != null && currentInvoice.invoiceDate.equals(rowDate));

                if (hasCustomer && !(sameCustomer && sameDate)) {
                    // Different customer or date -> close current, start fresh
                    finalizeInvoice(currentInvoice);
                    root.invoices.add(currentInvoice);
                    currentInvoice = openInvoice(invoiceSeq++, rowCustomerId, rowDate,
                            buildCustomerFromRow(row, cm));
                } else if (hasCustomer && sameCustomer && currentInvoice.invoiceDate == null && rowDate != null) {
                    currentInvoice.invoiceDate = rowDate;
                }
            }

            if (isVehicleCommentRow(row, cm)) {
                currentInvoice.vehicle = buildOrUpdateVehicle(currentInvoice.vehicle, row, cm);
            } else if (isLineItemRow(row, cm)) {
                InvoiceLine line = buildLineFromRow(row, cm);
                line.sortOrder = currentInvoice.lines.size();
                currentInvoice.lines.add(line);
            } else {
                String desc = safeGet(row, cm.itemDesc);
                if (!isBlank(desc)) {
                    if (currentInvoice.notes == null) currentInvoice.notes = "";
                    currentInvoice.notes += desc.trim() + '\n';
                }
            }
        }

        if (currentInvoice != null) {
            finalizeInvoice(currentInvoice);
            root.invoices.add(currentInvoice);
        }
    }

    // =========================================================================
    // NEW SAGE format  (NewSales.CSV)
    // =========================================================================

    /**
     * Each Sage invoice maps to one or more CSV rows sharing the same Customer ID +
     * Invoice/CM #.  Distribution 0 is a tax-header row (skipped as a line item).
     * Distributions >= 1 are the actual product/service lines.
     *
     * Amounts in this export are stored as negative AR entries; we negate them to
     * produce positive sale values.  Credit memos (Credit Memo = TRUE) are skipped.
     */
    private static void convertNewSage(List<String[]> rows, ColumnMap cm, Root root) {
        Invoice currentInvoice = null;
        String  currentKey     = null;
        int     invoiceSeq     = 1;

        for (int i = 1; i < rows.size(); i++) {
            String[] row = rows.get(i);
            if (isRowEmpty(row)) continue;

            String customerId = safeGet(row, cm.customerId);
            String invoiceNum = safeGet(row, cm.invoiceCmNum);
            if (isBlank(invoiceNum)) continue;

            String invoiceKey = customerId + "|" + invoiceNum;

            // ---- Open / close invoice on key change --------------------------------
            if (!invoiceKey.equals(currentKey)) {
                if (currentInvoice != null) {
                    computeTotalsFromLines(currentInvoice);
                    finalizeInvoice(currentInvoice);
                    if (hasLegitimateInvoiceLines(currentInvoice)) {
                        root.invoices.add(currentInvoice);
                    }
                }
                currentKey = invoiceKey;

                // Credit memos are not imported into the new system
                String creditMemo = safeGet(row, cm.creditMemo);
                if ("TRUE".equalsIgnoreCase(creditMemo)) {
                    currentInvoice = null;
                    continue;
                }

                currentInvoice = openInvoice(invoiceSeq++, customerId,
                        parseDate(safeGet(row, cm.date)), buildCustomerFromRowNew(row, cm));
                currentInvoice.sourceInvoiceNumber = invoiceNum;

                // Extract vehicle from Invoice Note on the first row of this invoice
                String note = safeGet(row, cm.invoiceNote);
                if (!isBlank(note)) {
                    Vehicle v = parseVehicleFromNote(note);
                    if (v != null) {
                        currentInvoice.vehicle = v;
                    } else {
                        currentInvoice.notes = note.trim() + "\n";
                    }
                }
            }

            if (currentInvoice == null) continue;  // skipping credit memo rows

            // Update customer display name when Ship to Name becomes available
            if (cm.shipToName >= 0) {
                String shipName = safeGet(row, cm.shipToName);
                if (!isBlank(shipName) && isBlank(currentInvoice.customer.name)) {
                    currentInvoice.customer.name = shipName;
                }
            }

            // ---- Distribution routing -----------------------------------------------
            int dist = parseIntSafe(safeGet(row, cm.invoiceDist));

            if (dist == 0) {
                // Distribution 0 = invoice-level tax header row.
                // Re-check Invoice Note in case it was blank when the invoice was opened.
                if (currentInvoice.vehicle == null) {
                    String note = safeGet(row, cm.invoiceNote);
                    if (!isBlank(note)) {
                        Vehicle v = parseVehicleFromNote(note);
                        if (v != null) currentInvoice.vehicle = v;
                    }
                }
                continue;
            }

            // dist >= 1: actual distribution line
            String itemId = safeGet(row, cm.itemId);
            String desc   = safeGet(row, cm.itemDesc);
            BigDecimal qty    = parseBigDecimal(safeGet(row, cm.qty));
            BigDecimal amount = parseBigDecimal(safeGet(row, cm.amount));

            // Ignore malformed data rows that have neither an Item ID nor a description.
            if (isBlank(itemId) && isBlank(desc)) continue;

            boolean zeroQty = qty    == null || BigDecimal.ZERO.compareTo(qty)    == 0;
            boolean zeroAmt = amount == null || BigDecimal.ZERO.compareTo(amount) == 0;

            // Zero-qty + zero-amount + no Item ID -> vehicle / note comment line
            if (isBlank(itemId) && zeroQty && zeroAmt) {
                if (!isBlank(desc)) {
                    Vehicle v = parseVehicleFromNote(desc);
                    if (v != null) {
                        currentInvoice.vehicle = mergeVehicle(currentInvoice.vehicle, v);
                    } else {
                        if (currentInvoice.notes == null) currentInvoice.notes = "";
                        currentInvoice.notes += desc.trim() + "\n";
                    }
                }
                continue;
            }

            // Real product / service line
            InvoiceLine line = buildLineFromRowNew(row, cm);
            line.sortOrder = currentInvoice.lines.size();
            currentInvoice.lines.add(line);
        }

        // Finalize the last open invoice
        if (currentInvoice != null) {
            computeTotalsFromLines(currentInvoice);
            finalizeInvoice(currentInvoice);
            if (hasLegitimateInvoiceLines(currentInvoice)) {
                root.invoices.add(currentInvoice);
            }
        }
    }

    // =========================================================================
    // Row-classification helpers  (LEGACY)
    // =========================================================================

    private static boolean isRowEmpty(String[] row) {
        for (String s : row) { if (!isBlank(s)) return false; }
        return true;
    }

    private static boolean isSummaryRow(String[] row, ColumnMap cm) {
        if (!isBlank(safeGet(row, cm.customerId))) return false;
        if (!isBlank(safeGet(row, cm.name)))       return false;
        if (!isBlank(safeGet(row, cm.itemId)))     return false;
        boolean hasNumeric = isNumeric(safeGet(row, cm.qty))
                || isNumeric(safeGet(row, cm.amount))
                || isNumeric(safeGet(row, cm.costOfSales));
        return hasNumeric && isBlank(safeGet(row, cm.itemDesc));
    }

    private static boolean isVehicleCommentRow(String[] row, ColumnMap cm) {
        String desc = safeGet(row, cm.itemDesc);
        if (isBlank(desc)) return false;
        if (!isBlank(safeGet(row, cm.itemId))) return false;
        boolean hasFinancials =
                isNumeric(safeGet(row, cm.qty))       || isNumeric(safeGet(row, cm.amount))
                || isNumeric(safeGet(row, cm.costOfSales)) || isNumeric(safeGet(row, cm.grossProfit))
                || isNumeric(safeGet(row, cm.grossMargin));
        if (hasFinancials) return false;
        String upper = desc.toUpperCase(Locale.ROOT);
        return upper.contains("MILEAGE")
                || upper.startsWith("VIN")
                || upper.contains("VIN:")
                || upper.matches(".*\\b(TOYOTA|HONDA|NISSAN|FORD|CHEVY|CHEVROLET|GMC|JEEP|DODGE"
                        + "|LEXUS|KIA|HYUNDAI|SUBARU|MERCEDES|BUICK|MAZDA|MASERATI"
                        + "|PONTIAC|CADILLAC|CHRYSLER|LINCOLN|ACURA|INFINITI|MITSUBISHI"
                        + "|VOLKSWAGEN|VW|BMW|AUDI|VOLVO|SUZUKI|HUMMER|MINI)\\b.*");
    }

    private static boolean isLineItemRow(String[] row, ColumnMap cm) {
        if (!isBlank(safeGet(row, cm.itemId))) return true;
        return isNumeric(safeGet(row, cm.qty)) || isNumeric(safeGet(row, cm.amount));
    }

    // =========================================================================
    // Builders  (shared + LEGACY)
    // =========================================================================

    private static Invoice openInvoice(int seq, String customerId, LocalDate date, Customer customer) {
        Invoice inv = new Invoice();
        inv.invoiceId        = startId + seq;
        inv.sourceCustomerId = customerId;
        inv.invoiceDate      = date;
        inv.customer         = customer;
        return inv;
    }

    private static Customer buildCustomerFromRow(String[] row, ColumnMap cm) {
        Customer c = new Customer();
        c.customerId    = safeGet(row, cm.customerId);
        c.name          = safeGet(row, cm.name);
        c.billToContact = safeGet(row, cm.billToContact);
        c.phone         = normalizePhone(safeGet(row, cm.phone));
        return c;
    }

    private static String normalizePhone(String raw) {
        if (raw == null) return null;
        String digits = raw.replaceAll("\\D", "");
        if (digits.isEmpty()) return null;
        if (digits.length() == 11 && digits.startsWith("1")) digits = digits.substring(1);
        return digits;
    }

    /**
     * Updates (or creates) a Vehicle from a legacy comment row.
     * Handles:
     *   • VIN lines     – "VIN: 3MZBM1L70FM217353"
     *   • Mileage lines – "2015 MAZDA 3 MILES: 117,308"
     */
    private static Vehicle buildOrUpdateVehicle(Vehicle existing, String[] row, ColumnMap cm) {
        String desc = safeGet(row, cm.itemDesc);
        if (isBlank(desc)) return existing;

        String upper = desc.toUpperCase(Locale.ROOT);
        boolean isVin     = upper.startsWith("VIN") || upper.contains("VIN:") || upper.startsWith("VIN#");
        boolean isMileage = upper.contains("MILEAGE") || upper.contains("MILES:");

        if (!isVin && !isMileage) return existing;
        if (existing == null) existing = new Vehicle();

        if (isVin) {
            String vin = desc.replace("VIN#","").replace("VIN:","").replace("VIN","")
                    .replace("vin#","").replace("vin:","").replace("vin","")
                    .replace(":"," ").trim().replaceAll("\\s+","");
            if (!isBlank(vin) && isBlank(existing.vin)) existing.vin = vin;
            return existing;
        }

        // Mileage line: "2015 MAZDA 3 MILES: 117,308"
        String text   = desc.trim();
        String upper2 = text.toUpperCase(Locale.ROOT);
        int mileIdx   = upper2.indexOf("MILE");
        int cutIdx    = mileIdx >= 0 ? mileIdx : text.length();
        String left   = text.substring(0, cutIdx).trim();
        String right  = text.substring(cutIdx).trim();

        String[] tokens = left.split("\\s+");
        int year = 0, yearIdx = -1;
        for (int k = 0; k < tokens.length; k++) {
            String d = tokens[k].replaceAll("[^0-9]","");
            if (d.length() == 4 && d.matches("\\d{4}")) {
                year = Integer.parseInt(d); yearIdx = k; break;
            }
        }

        String make = null, model = null;
        if (yearIdx >= 0 && yearIdx + 1 < tokens.length) {
            StringBuilder mm = new StringBuilder();
            for (int j = yearIdx + 1; j < tokens.length; j++) {
                if (mm.length() > 0) mm.append(' ');
                mm.append(tokens[j].replaceAll(",",""));
            }
            String mmStr = mm.toString().trim();
            if (!mmStr.isEmpty()) {
                String[] parts = mmStr.split("\\s+", 2);
                make = parts[0];
                if (parts.length > 1) model = parts[1];
            }
        }

        if (year != 0) existing.year = year;
        if (make  != null) existing.make  = make;
        if (model != null) existing.model = model;

        String milesDigits = right.replaceAll("[^0-9]","");
        if (!milesDigits.isEmpty()) {
            try { existing.mileage = Integer.parseInt(milesDigits); }
            catch (NumberFormatException ignored) {}
        }

        if (existing.description == null && year != 0 && make != null) existing.description = text;
        return existing;
    }

    private static InvoiceLine buildLineFromRow(String[] row, ColumnMap cm) {
        InvoiceLine line = new InvoiceLine();
        line.itemId             = safeGet(row, cm.itemId);
        line.itemDescription    = safeGet(row, cm.itemDesc);
        line.stockingUm         = safeGet(row, cm.stockingUm);
        line.qty                = parseBigDecimal(safeGet(row, cm.qty));
        line.amount             = parseBigDecimal(safeGet(row, cm.amount));
        line.costOfSales        = parseBigDecimal(safeGet(row, cm.costOfSales));
        line.grossProfit        = parseBigDecimal(safeGet(row, cm.grossProfit));
        line.grossMarginPercent = parseBigDecimal(safeGet(row, cm.grossMargin));
        line.serialNumber       = safeGet(row, cm.serialNumber);
        line.serialNumberStatus = safeGet(row, cm.serialStatus);
        line.itemType           = safeGet(row, cm.itemType);
        line.itemCategory       = safeGet(row, cm.itemCategory);
        line.isCommentOnly      = (line.qty == null || BigDecimal.ZERO.compareTo(line.qty) == 0)
                && line.amount == null && !isBlank(line.itemDescription);
        return line;
    }

    private static void applySummaryToInvoice(Invoice invoice, String[] row, ColumnMap cm) {
        invoice.totalQty                = parseBigDecimal(safeGet(row, cm.qty));
        invoice.totalAmount             = parseBigDecimal(safeGet(row, cm.amount));
        invoice.totalCostOfSales        = parseBigDecimal(safeGet(row, cm.costOfSales));
        invoice.totalGrossProfit        = parseBigDecimal(safeGet(row, cm.grossProfit));
        invoice.totalGrossMarginPercent = parseBigDecimal(safeGet(row, cm.grossMargin));
    }

    // =========================================================================
    // Builders  (NEW SAGE)
    // =========================================================================

    private static Customer buildCustomerFromRowNew(String[] row, ColumnMap cm) {
        Customer c = new Customer();
        c.customerId = safeGet(row, cm.customerId);
        // Prefer "Ship to Name" as the display name; fall back to Customer ID
        String shipName = safeGet(row, cm.shipToName);
        c.name          = !isBlank(shipName) ? shipName : c.customerId;
        c.phone         = null;   // not available in this export
        c.billToContact = null;
        return c;
    }

    private static InvoiceLine buildLineFromRowNew(String[] row, ColumnMap cm) {
        InvoiceLine line = new InvoiceLine();
        line.itemId          = safeGet(row, cm.itemId);
        line.itemDescription = safeGet(row, cm.itemDesc);
        line.stockingUm      = safeGet(row, cm.stockingUm);
        line.qty             = parseBigDecimal(safeGet(row, cm.qty));
        line.serialNumber    = safeGet(row, cm.serialNumber);

        // Amounts in this Sage export are negative AR entries; negate to get the sale value.
        BigDecimal raw = parseBigDecimal(safeGet(row, cm.amount));
        line.amount = (raw != null) ? raw.negate() : null;

        // Cost-of-sales / GP not available in this format
        line.costOfSales        = null;
        line.grossProfit        = null;
        line.grossMarginPercent = null;
        line.serialNumberStatus = null;
        line.itemType           = null;
        line.itemCategory       = null;

        line.isCommentOnly = (line.qty == null || BigDecimal.ZERO.compareTo(line.qty) == 0)
                && line.amount == null && !isBlank(line.itemDescription);
        return line;
    }

    /**
     * Parse a Vehicle from free-text (Invoice Note or zero-amount comment lines).
     *
     * Handles patterns like:
     *   "2003 CHEVY FULL CONVERSION VAN"
     *   "DISCOVER 1998 TOYOTA AVALON"         payment prefix before year
     *   "2001 TOYOTA SONOTA VISA DEBIT"        payment suffix after model
     *   "1988 TOYOTA PICK UP 4x4"
     *
     * Returns null when no vehicle year can be found.
     */
    private static Vehicle parseVehicleFromNote(String text) {
        if (isBlank(text)) return null;

        Set<String> paymentWords = new HashSet<>(Arrays.asList(
                "DISCOVER","VISA","MASTERCARD","AMEX","CASH","CHECK","DEBIT","CREDIT","MC","DINERS"
        ));

        String upper  = text.toUpperCase(Locale.ROOT).trim();
        String[] toks = upper.split("\\s+");

        // Find first token that looks like a vehicle year (1960-2035)
        int yearIndex = -1, year = 0;
        for (int i = 0; i < toks.length; i++) {
            String d = toks[i].replaceAll("[^0-9]","");
            if (d.length() == 4) {
                try {
                    int y = Integer.parseInt(d);
                    if (y >= 1960 && y <= 2035) { year = y; yearIndex = i; break; }
                } catch (NumberFormatException ignored) {}
            }
        }
        if (year == 0 || yearIndex + 1 >= toks.length) return null;

        // Collect tokens after the year, stopping at the first payment keyword
        List<String> rest = new ArrayList<>();
        for (int i = yearIndex + 1; i < toks.length; i++) {
            if (paymentWords.contains(toks[i])) break;
            rest.add(toks[i]);
        }
        if (rest.isEmpty()) return null;

        Vehicle v = new Vehicle();
        v.year  = year;
        v.make  = rest.get(0);
        if (rest.size() > 1) v.model = String.join(" ", rest.subList(1, rest.size()));
        v.description = year + " " + v.make + (v.model != null ? " " + v.model : "");
        return v;
    }

    /** Merge newV into existing, only filling in fields that are absent in existing. */
    private static Vehicle mergeVehicle(Vehicle existing, Vehicle newV) {
        if (existing == null) return newV;
        if (newV     == null) return existing;
        if (existing.year == 0    && newV.year  != 0)    existing.year  = newV.year;
        if (isBlank(existing.make)  && !isBlank(newV.make))  existing.make  = newV.make;
        if (isBlank(existing.model) && !isBlank(newV.model)) existing.model = newV.model;
        if (isBlank(existing.vin)   && !isBlank(newV.vin))   existing.vin   = newV.vin;
        if (existing.mileage == 0  && newV.mileage != 0)  existing.mileage = newV.mileage;
        if (isBlank(existing.description) && !isBlank(newV.description))
            existing.description = newV.description;
        return existing;
    }

    /**
     * Compute totalAmount and totalQty from line items.
     * Used by the New Sage format which has no dedicated summary row.
     * Amounts have already been negated to positive sale values at this point.
     */
    private static void computeTotalsFromLines(Invoice inv) {
        BigDecimal sumAmt = BigDecimal.ZERO;
        BigDecimal sumQty = BigDecimal.ZERO;
        for (InvoiceLine l : inv.lines) {
            if (l.amount != null) sumAmt = sumAmt.add(l.amount);
            if (l.qty    != null) sumQty = sumQty.add(l.qty);
        }
        inv.totalAmount = sumAmt;
        inv.totalQty    = sumQty;
    }

    /** Null out vehicles that lack year+make+model, and trim notes whitespace. */
    private static void finalizeInvoice(Invoice inv) {
        if (!hasMinimalVehicle(inv.vehicle)) inv.vehicle = null;
        if (inv.notes != null) {
            inv.notes = inv.notes.trim();
            if (inv.notes.isEmpty()) inv.notes = null;
        }
    }

    private static boolean hasLegitimateInvoiceLines(Invoice inv) {
        if (inv == null || inv.lines == null || inv.lines.isEmpty()) return false;
        for (InvoiceLine line : inv.lines) {
            if (line == null) continue;
            if (!isBlank(line.itemId) || !isBlank(line.itemDescription)) return true;
        }
        return false;
    }

    // =========================================================================
    // Utility methods
    // =========================================================================

    private static String safeGet(String[] row, int idx) {
        if (row == null || idx < 0 || idx >= row.length) return "";
        String v = row[idx];
        return v == null ? "" : v.trim();
    }

    private static boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }

    private static boolean isNumeric(String s) {
        if (isBlank(s)) return false;
        try { new BigDecimal(s.replace(",","")); return true; }
        catch (NumberFormatException e) { return false; }
    }

    private static BigDecimal parseBigDecimal(String s) {
        if (isBlank(s)) return null;
        try { return new BigDecimal(s.replace(",","")); }
        catch (NumberFormatException e) { return null; }
    }

    private static LocalDate parseDate(String s) {
        if (isBlank(s)) return null;
        s = s.trim();
        try { return LocalDate.parse(s, DATE_FMT);    } catch (Exception ignored) {}
        try { return LocalDate.parse(s, DATE_FMT_4Y); } catch (Exception ignored) {}
        return null;
    }

    private static int parseIntSafe(String s) {
        if (isBlank(s)) return -1;
        try { return Integer.parseInt(s.trim()); }
        catch (NumberFormatException e) { return -1; }
    }

    private static boolean hasMinimalVehicle(Vehicle v) {
        if (v == null) return false;
        return v.year != 0 && !isBlank(v.make) && !isBlank(v.model);
    }
}
